#!/usr/bin/env bash

if [ ! -d "$HOME/.nano/nanorc" ]; then
  echo "installing nanorc..."
  git clone git@github.com:scopatz/nanorc.git "$HOME/.nano/nanorc"
else
  echo "skipping nanorc: already installed"
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  echo "installing tpm..."
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
  ~/.tmux/plugins/tpm/bin/install_plugins
else
  echo "skipping tpm: already installed"
fi

if [ ! -d "$HOME/.tfenv" ]; then
  echo "installing tfenv..."
  git clone https://github.com/tfutils/tfenv.git "$HOME/.tfenv"
else
  echo "skipping tfenv: already installed"
fi
