#!/usr/bin/env bash

echo "installing nanorc..."
git clone git@github.com:scopatz/nanorc.git "~/.nano/nanorc"

echo "installing tpm..."
git clone https://github.com/tmux-plugins/tpm "~/.tmux/plugins/tpm"
